# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

plugins: rubocop-rspec

# Overwrite or add rules to create your own house style
#
RSpec/MultipleExpectations:
  Max: 20
